/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 computer.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/computer-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Cube" position={[0.658, 1.336, -18.759]} rotation={[0, 1.536, 0]} scale={0.969}>
          <mesh name="Cube_1" geometry={nodes.Cube_1.geometry} material={materials.Wall} />
          <mesh name="Cube_2" geometry={nodes.Cube_2.geometry} material={materials['Wall Two']} />
        </group>
        <group name="Computer" position={[-7.952, 6.725, -1.05]} rotation={[-Math.PI, 0.823, -Math.PI]}>
          <mesh name="Cube021" geometry={nodes.Cube021.geometry} material={materials.Computer} />
          <mesh name="Cube021_1" geometry={nodes.Cube021_1.geometry} material={materials.Screen} />
        </group>
        <group name="Shelves" position={[-10.168, 12.059, 0.303]} rotation={[-Math.PI, 0.823, -Math.PI]}>
          <mesh name="Cylinder010" geometry={nodes.Cylinder010.geometry} material={materials.lamps} />
          <mesh name="Cylinder010_1" geometry={nodes.Cylinder010_1.geometry} material={materials.Profile} />
          <mesh name="Cylinder010_2" geometry={nodes.Cylinder010_2.geometry} material={materials['profile pic']} />
          <mesh name="Cylinder010_3" geometry={nodes.Cylinder010_3.geometry} material={materials.Material} />
          <mesh name="Cylinder010_4" geometry={nodes.Cylinder010_4.geometry} material={materials.Book} />
          <mesh name="Cylinder010_5" geometry={nodes.Cylinder010_5.geometry} material={materials.book7} />
          <mesh name="Cylinder010_6" geometry={nodes.Cylinder010_6.geometry} material={materials.Book2} />
          <mesh name="Cylinder010_7" geometry={nodes.Cylinder010_7.geometry} material={materials['Table Top.002']} />
          <mesh name="Cylinder010_8" geometry={nodes.Cylinder010_8.geometry} material={materials['pen 3']} />
        </group>
        <group name="Table_Stuff" position={[-7.615, 5.036, -0.729]} rotation={[-Math.PI, 0.823, -Math.PI]}>
          <mesh name="Cube114" geometry={nodes.Cube114.geometry} material={materials.Pot} />
          <mesh name="Cube114_1" geometry={nodes.Cube114_1.geometry} material={materials['Leaf.002']} />
          <mesh name="Cube114_2" geometry={nodes.Cube114_2.geometry} material={materials.Leaf} />
          <mesh name="Cube114_3" geometry={nodes.Cube114_3.geometry} material={materials['Mini.001']} />
          <mesh name="Cube114_4" geometry={nodes.Cube114_4.geometry} material={materials.pen2} />
          <mesh name="Cube114_5" geometry={nodes.Cube114_5.geometry} material={materials.pen1} />
          <mesh name="Cube114_6" geometry={nodes.Cube114_6.geometry} material={materials.Trackpad} />
          <mesh name="Cube114_7" geometry={nodes.Cube114_7.geometry} material={materials['Material.001']} />
          <mesh name="Cube114_8" geometry={nodes.Cube114_8.geometry} material={materials.drink} />
          <mesh name="Cube114_9" geometry={nodes.Cube114_9.geometry} material={materials.Mini} />
          <mesh name="Cube114_10" geometry={nodes.Cube114_10.geometry} material={materials.Dirt} />
          <mesh name="Cube114_11" geometry={nodes.Cube114_11.geometry} material={materials.Key} />
        </group>
        <mesh name="fish" geometry={nodes.fish.geometry} material={materials.Fish} position={[10.394, 5.197, 2.022]} rotation={[-Math.PI, 0.748, -Math.PI]} />
        <mesh name="Desks" geometry={nodes.Desks.geometry} material={materials['Table Leg Black.002']} position={[-5.602, 2.58, -0.817]} rotation={[-Math.PI, 0.823, -Math.PI]} />
        <group name="Lamp" position={[-7.007, -0.455, 10.197]} rotation={[-Math.PI, 0.823, -Math.PI]}>
          <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials.fdsa} />
          <mesh name="Plane010_1" geometry={nodes.Plane010_1.geometry} material={materials.lamp} />
        </group>
        <mesh name="FloorThird" geometry={nodes.FloorThird.geometry} material={materials['seas.003']} position={[-7.253, -0.498, 15.16]} rotation={[-Math.PI, -0.748, -Math.PI]} />
        <mesh name="FloorSecond" geometry={nodes.FloorSecond.geometry} material={materials.Fish} position={[-6.587, -0.498, 13.428]} rotation={[-Math.PI, -0.748, -Math.PI]} />
        <mesh name="FloorFirst" geometry={nodes.FloorFirst.geometry} material={materials['seas.004']} position={[-4.928, -0.498, 12.76]} rotation={[-Math.PI, -0.748, -Math.PI]} />
        <mesh name="Floor_Items" geometry={nodes.Floor_Items.geometry} material={materials['Trash Lid']} position={[-2.855, -0.214, 1.604]} rotation={[-Math.PI, 0.823, -Math.PI]} />
        <group name="Aquarium" position={[7.682, 1.61, 0.81]} rotation={[-Math.PI, 0.823, -Math.PI]}>
          <mesh name="Cube136" geometry={nodes.Cube136.geometry} material={materials['water.001']} />
          <mesh name="Cube136_1" geometry={nodes.Cube136_1.geometry} material={materials.tanke} />
          <mesh name="Cube136_2" geometry={nodes.Cube136_2.geometry} material={materials.Rock} />
          <mesh name="Cube136_3" geometry={nodes.Cube136_3.geometry} material={materials.seas} />
          <mesh name="Cube136_4" geometry={nodes.Cube136_4.geometry} material={materials['seas.002']} />
          <mesh name="Cube136_5" geometry={nodes.Cube136_5.geometry} material={materials['seas.001']} />
          <mesh name="Cube136_6" geometry={nodes.Cube136_6.geometry} material={materials.seaweed} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/computer-transformed.glb')
