/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 laptop.glb
Author: LuddePudde (https://sketchfab.com/ludde5000)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyberputer-d48db2dba37b4fb394eb0839a2077228
Title: Cyberputer
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/laptop.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.kablar} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.natagg} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.dator} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/laptop.glb')
